---
title: "Plots for cellular processes permutation results"
output: html_document
---

#
```{r}
#Load libraries
library(dplyr)
library(tibble)
library(tidyr)
library(reshape2)
library(ggplot2)

setwd("/Users/mary/Documents/research/exps/exp060_chaitanya/")
#here::set_here("/Users/mary/Documents/research/exps/exp060_chaitanya/")
library(here)

#Load dataset
load("/Users/mary/Documents/research/exps/exp060_chaitanya/res/2024/data/gene_group_perm_data.Rdata")
```

```{r}

# Define the labels for the Y-axis categories and X-axis datasets
y_labels <- c("rib" = "Ribosomes", 
              "mt" = "Mitochondrial", 
              "nmt" = "Nuclear mitochondrial", 
              "etc" = "OXPHOS (ETC)", 
              "h_rd" = "Replication-dependent histones", 
              "h_ri" = "Replication-independent histones", 
              "cy_g1" = "Cell cycle - G1 Phase", 
              "cy_g1s" = "Cell cycle - G1/S Phase", 
              "cy_s" = "Cell cycle - S Phase", 
              "cy_g2" = "Cell cycle - G2 Phase", 
              "cy_g2m" = "Cell cycle - G2/M Phase", 
              "cy_m" = "Cell cycle - M Phase")

x_labels <- c("b" = "BIODEP", 
              "d" = "dbGaP", 
              "g" = "HiTDiP", 
              "l" = "Le", 
              "m" = "Mostafavi")

all_male_fem_perm$sig <- factor(ifelse(all_male_fem_perm$FDR<0.01, "FDR<0.01", ifelse(all_male_fem_perm$FDR<0.05, "FDR<0.05","Not sig")), levels=c("Not sig","FDR<0.05","FDR<0.01"), ordered=T)

all_male_fem_perm %>%
  ggplot(aes(x = dataset, 
             y = factor(category, levels = c("rib", "mt", "nmt", "etc", "h_rd", "h_ri",
                                             "cy_g1", "cy_g1s", "cy_s", "cy_g2", "cy_g2m", "cy_m")), 
             fill = as.numeric(directionlogFC), size = sig)) + 
  geom_point(shape = 22) + 
  theme_minimal() + 
  facet_grid(~Sex) + 
  scale_y_discrete(labels = y_labels, limits = rev) + 
  scale_x_discrete(labels = x_labels) + 
  theme(strip.background = element_rect(fill = "black"), 
        strip.text = element_text(color =  "white", face = "bold"), 
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle=45, hjust=1, size=12)) + 
  scale_size_manual(values=c(3,7,9)) +
  scale_fill_gradientn(colours = c("steelblue4", "steelblue2", "white", "red2", "red4"), 
                       limits = c(-0.35, 0.35), values=c(0, 0.4, 0.5, -0.6, 1)) + 
#  scale_size(breaks = c(0.01, 0.05, 0.049), limits = c(0,0.1), range = c(10,3), labels=c("FDR<0.01","FDR<0.05","FDR>0.05")) + 
  xlab("") + ylab("") + labs(fill = "LFC", size = "Significance") 

ggsave("all_perm_male_fem_sep_plot_break.pdf", path=here("pics/"), width = 8, height = 5) 
```

```{r}
#Male female separate meta-analysed result plot
wz_res_tot_plot$sig <- factor(ifelse(wz_res_tot_plot$FDR<0.01, "FDR<0.01", ifelse(wz_res_tot_plot$FDR<0.05, "FDR<0.05","Not sig")), levels=c("Not sig","FDR<0.05","FDR<0.01"), ordered=T)

wz_res_tot_plot %>% 
  ggplot(aes(x = dataset, 
             y = factor(category_name, levels = c("rib", "mt", "nmt", "etc", "h_rd", "h_ri", 
                                                  "cy_g1", "cy_g1s", "cy_s", "cy_g2", "cy_g2m", "cy_m")), 
             fill = as.numeric(weighted_mean), size = sig)) + 
  scale_y_discrete(labels = y_labels, limits = rev) + 
  scale_x_discrete(labels = x_labels) + 
  geom_point(shape = 22) + theme_minimal() + facet_grid(~Sex) + 
  theme(strip.background = element_rect(fill = "black"), 
        strip.text = element_text(color =  "white", face = "bold"), 
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle=45, hjust=1, size=12)) + 
    scale_size_manual(values=c(3,7,9)) +
  scale_fill_gradientn(colours = c("steelblue4", "steelblue2", "white", "red2", "red4"),
                       limits = c(-0.35, 0.35), values=c(0, 0.4, 0.5, -0.6, 1)) + 
  #scale_size(breaks = c(0.01, 0.01, 0.049), limits = c(0,0.1), range = c(10,3), labels=c("FDR<0.01","FDR<0.05","Not sig")) + 
  xlab("") + ylab("") + labs(fill = "LFC", size = "Significance") 
ggsave("meta_male_fem_sep_plot_break.pdf", path=here("pics/"), width = 5.7, height = 5) 
```


```{r}
#Pooled plot
all_pooled_perm_BH$sig <- factor(ifelse(all_pooled_perm_BH$FDR<0.01, "FDR<0.01", ifelse(all_pooled_perm_BH$FDR<0.05, "FDR<0.05","Not sig")), levels=c("Not sig","FDR<0.05","FDR<0.01"), ordered=T)

all_pooled_perm_BH %>% 
  ggplot(aes(x = dataset, y = factor(category, levels = c("rib", "mt", "nmt", "etc", "h_rd", "h_ri", 
                                                          "cy_g1", "cy_g1s", "cy_s", "cy_g2", "cy_g2m", "cy_m")), 
             fill = as.numeric(directionlogFC), size = sig)) + 
  scale_y_discrete(labels = y_labels, limits = rev) + 
  scale_x_discrete(labels = x_labels) + 
  geom_point(shape = 22) + theme_minimal() + facet_grid(~Sex) +  
  theme(strip.background = element_rect(fill = "black"), 
        strip.text = element_text(color =  "white", face = "bold"), 
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle=45, hjust=1, size=12)) + 
    scale_size_manual(values=c(3,7,9)) +
  scale_fill_gradientn(colours = c("steelblue4", "steelblue2", "white", "red2", "red4"),
                       limits = c(-0.35, 0.35), values=c(0, 0.4, 0.5, -0.6, 1)) + # scale_size(breaks = c(0.01, 0.05, 0.049), limits = c(0,0.1), range = c(10,3), labels=c("FDR<0.01","FDR<0.05","Not sig")) + 
  xlab("") + ylab("") + labs(fill = "LFC", size = "Significance") 
ggsave("all_perm_pooled_sep_plot_break.pdf", path=here("pics/"), width = 5.5, height = 5) 

#Pooled meta-analysed result plot
wz_res_tot_plot_p$sig <- factor(ifelse(wz_res_tot_plot_p$FDR<0.01, "FDR<0.01", ifelse(wz_res_tot_plot_p$FDR<0.05, "FDR<0.05","Not sig")), levels=c("Not sig","FDR<0.05","FDR<0.01"), ordered=T)

wz_res_tot_plot_p %>% 
  ggplot(aes(x = dataset, y = factor(category, levels = c("rib", "mt", "nmt", "etc", "h_rd", "h_ri",
                                                          "cy_g1", "cy_g1s", "cy_s", "cy_g2", "cy_g2m", "cy_m")), 
             fill = as.numeric(weighted_mean_pooled), size = sig)) + 
  scale_y_discrete(labels = y_labels, limits = rev) +
  scale_x_discrete(labels = x_labels) + 
  geom_point(shape = 22) + theme_minimal() + facet_grid(~Sex) +  
  theme(strip.background = element_rect(fill = "black"), 
        strip.text = element_text(color =  "white", face = "bold"), 
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle=45, hjust=1, size=12)) + 
  scale_fill_gradientn(colours = c("steelblue4", "steelblue2", "white", "red2", "red4"), 
                       limits = c(-0.35, 0.35), values=c(0, 0.4, 0.5, -0.6, 1)) + scale_size_manual(values=c(3,7,9)) +
  #scale_size(breaks = c(0.01, 0.01, 0.049), limits = c(0,0.1), range = c(10,3), labels=c("FDR<0.01","FDR<0.01","FDR>0.05")) + 
  xlab("") + ylab("") + labs(fill = "LFC", size = "Significance") 
ggsave("meta_pooled_sep_plot_break.pdf", path=here("pics/"), width = 4.7, height = 5) 

```


