---
title: "HiTDiP data processing"
output: html_notebook
---

Loading required libraries


```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(reshape2)
library(tibble)
library(biomaRt)
library(affy) #1.68.0
library(hgu133plus2.db) #3.2.3
library(arrayQualityMetrics) #3.46.0
library(jetset) #3.4.0
```


Read metadata 

```{r}
final_metadata <- read.table("hitdip_metadata.txt", stringsAsFactors = F, header = T, sep = "\t", skip = 41, nrows = 36) %>% mutate(Disorder = if_else(disorder == "whole_blood_control", "CNT", "MDD"), Anxiety = if_else(anxiety == "anxiety: no", "0", "1"), Sex = if_else(sex == "gender: M", "Male", "Female"), Batch = if_else(batch == "batch: 1", "1", "2")) %>% separate(age, into = c(NA, "Age"), sep = ":", remove = F) %>% dplyr::select(GEO_SAMPID, Disorder:Batch, Age)
metadata[,c(2:5)] <- lapply(metadata[,c(2:5)], factor)
metadata$Age <- as.numeric(metadata$Age)

```

Create eset and phenodata

```{r}
filenames <- list.files("raw_data/", pattern = ".CEL") %>% as.data.frame() %>% setNames("names") %>% separate(names, into = c("id", NA), sep = "_", remove = F)

phenodata <- metadata %>% rownames_to_column("Vs") %>% dplyr::select(-Vs) %>% merge(., filenames, by.x = "GEO_SAMPID", by.y = "id") %>% column_to_rownames("names") %>% AnnotatedDataFrame()
filenames <- list.files("raw_data/", pattern = ".CEL")

eset <- justRMA(phenoData = phenodata, celfile.path = "raw_data/")
```

Add gene annotations and removed unannotated probes and probes that match to multiple genes

```{r}
eset_annotation <- AnnotationDbi::select(hgu133plus2.db, keys = (featureNames(eset)), columns = c("SYMBOL", "GENENAME"), keytype = "PROBEID")

ids_multi_map <- eset_annotation %>% group_by(PROBEID) %>% summarise(no_of_matches = n_distinct(SYMBOL)) %>% filter(no_of_matches > 1) %>% ungroup() %>% dplyr::select(PROBEID) 
ids_unannoted <- eset_annotation %>% filter(is.na(SYMBOL) == T) %>% dplyr::select(PROBEID) 
ids_to_remove <- rbind(ids_multi_map, ids_unannoted)

ids_to_exclude <- (featureNames(eset) %in% ids_to_remove$PROBEID)
```

```{r}
eset_2 <- subset(eset, !ids_to_exclude)
validObject(eset_2)

fData(eset_2)$PROBEID <- rownames(fData(eset_2))

fData(eset_2) <- left_join(fData(eset_2), eset_annotation)
rownames(fData(eset_2)) <- fData(eset_2)$PROBEID
```

Quality control using arrayQualityMetrics

```{r}
#Visual:
arrayQualityMetrics(expressionset = eset_2, outdir = "hitdip_qc_metrics", reporttitle = "Qualtiy metrics for HiTDiP", intgroup = c("Disorder", "Batch", "Sex", "Anxiety"))

browseURL(file.path("hitdip_qc_metrics", "index.html"))

#doing them separately

preparedData <- prepdata(expressionset = eset_2, intgroup = "Disorder", do.logtransform = F)

#Outlier 1:
library(genefilter)
m   = genefilter::dist2(preparedData$M)
out = outliers(m, method = "sum")
out@description = c("sum of distances to other arrays <i>S<sub>a</sub></i>", "data-driven")

#Outlier 2:
out2 = outliers(preparedData$M, method = "KS")
out2@description = c("Kolmogorov-Smirnov statistic <i>K<sub>a</sub></i>", "data-driven")

#Outlier 3:
ma = aqm.maplot(preparedData)
#no outliers identified using third method

outlier1 <- out@which %>% as.data.frame() %>% rownames_to_column() %>% setNames(c("sample_id", "stat"))
outlier2 <- out2@which %>% as.data.frame() %>% rownames_to_column() %>% setNames(c("sample_id", "stat"))
outliers <- rbind(outlier1, outlier2) %>% dplyr::select(sample_id) %>% distinct(sample_id)

eset_3 = eset_2[, !sampleNames(eset_2) %in% final_outliers$samp_name]
validObject(eset_3)


rm(outlier1, outlier2)
```

Re-normalisation

```{r}
final_metadata <- phenoData(eset_3)@data
phenodata <- phenoData(eset_3)
filenames <- final_metadata %>% rownames_to_column("names") %>% dplyr::select(names) %>% mutate(path = paste("raw_data/", names, sep =""))
filenames <- as.character(filenames$path)

eset_fin <- justRMA(phenoData = phenodata, filenames = filenames)
```

Create final dataset

```{r}

eset_fin <- subset(eset_fin, !ids_to_exclude)
validObject(eset_fin)

fData(eset_fin)$PROBEID <- rownames(fData(eset_fin))

fData(eset_fin) <- left_join(fData(eset_fin), eset_annotation)
rownames(fData(eset_fin)) <- fData(eset_fin)$PROBEID 

final_metadata <- phenoData(eset_3)@data %>% rownames_to_column("sample_id_match")
```

